-- AlterEnum: add new CareContext values
ALTER TYPE "CareContext" ADD VALUE IF NOT EXISTS 'CARDIAC_FOLLOWUP';
ALTER TYPE "CareContext" ADD VALUE IF NOT EXISTS 'DIABETES_MANAGEMENT';
ALTER TYPE "CareContext" ADD VALUE IF NOT EXISTS 'HYPERTENSION_MONITORING';
ALTER TYPE "CareContext" ADD VALUE IF NOT EXISTS 'MATERNAL_CARE';
ALTER TYPE "CareContext" ADD VALUE IF NOT EXISTS 'MENTAL_HEALTH_FOLLOWUP';
ALTER TYPE "CareContext" ADD VALUE IF NOT EXISTS 'PEDIATRIC_FOLLOWUP';
ALTER TYPE "CareContext" ADD VALUE IF NOT EXISTS 'ONCOLOGY_FOLLOWUP';
ALTER TYPE "CareContext" ADD VALUE IF NOT EXISTS 'RENAL_FOLLOWUP';
